language: go

go:
    - tip

before_install:
    - go get golang.org/x/tools/cmd/cover
    
install:
    - go get github.com/stretchr/testify/assert
    - go get github.com/julienschmidt/httprouter

script:
    - go test -cover

notifications:
    email: false
